default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 0407
  host: localhost
  port: 5432

development:
  <<: *default
  database: library_app_development  # Имя базы для разработки

test:
  <<: *default
  database: library_app_test  # Имя базы для тестов

production:
  <<: *default
  database: library_app_production  # Имя базы для продакшена
#  username: your_production_user
#  password: your_production_password
