default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: library_app_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST']     || 'localhost' %>
  port:     <%= ENV['DB_PORT']     || 5432 %>

test:
  <<: *default
  database: library_app_test
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST']     || 'localhost' %>
  port:     <%= ENV['DB_PORT']     || 5432 %>

production:
  <<: *default

  # основная база (для ActiveRecord)
  primary:
    url: <%= ENV['DATABASE_URL'] %>

  # для Solid Cable (если используется)
  cable:
    url: <%= ENV['DATABASE_URL'] %>

  # для Solid Queue
  queue:
    url: <%= ENV['DATABASE_URL'] %>

